apiVersion: v1
kind: Namespace
metadata:
  name: requestbin

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: requestbin
spec:
  selector:
    app: redis
  ports:
  - port: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: requestbin
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0@sha256:c389a35832492c42f4719776471f9a42d2fc5a8ba0077ba25746626b09eab880
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: requestbin
  namespace: requestbin
spec:
  type: NodePort
  selector:
    app: requestbin
  ports:
  - port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestbin
  namespace: requestbin
  labels:
    app: requestbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestbin
  template:
    metadata:
      labels:
        app: requestbin
    spec:
      containers:
      - name: requestbin
        image: crccheck/requestbin@sha256:a3dfaa2c2ace47cdcd2add65621e8ad343e5b58819878f6a42f80fd25e9321e5
        ports:
        - containerPort: 80
        env:
        - name: REDIS_URL
          value: redis://redis:6379/0
